version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./scripts:/app/scripts
    env_file:
      - ./config/env_prod.py
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: leads_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: