# Usa una imagen base de Python
FROM python:3.10-slim

# Establece el directorio de trabajo
WORKDIR /app

# Copia el archivo de requisitos y el código fuente al contenedor
COPY requirements.txt .

# Instala las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copia el resto del código fuente
COPY . .

# Expone el puerto en el que FastAPI escuchará
EXPOSE 8000

# Comando para ejecutar la aplicación
CMD ["uvicorn", "main:app","--reload", "--host", "0.0.0.0", "--port", "8000"]